title: Guqin Book
description: For Global Learners
theme: just-the-docs

url: https://guqinx.com

# aux_links:
#  Find Tablature: https://guqintab.com

# Footer content
# appears at the bottom of every page's main content

# Back to top link
# back_to_top: true
# back_to_top_text: Back to top
# footer_content: Write to me GuqinX@gmail.com

